name: CodeWhitelist
version: '${version}'
main: com.spectrasonic.CodeWhitelist.Main
api-version: '1.20'
authors:
  - Spectrasonic
commands:
  code:
    description: Verifies the player's code.
    usage: /code <code>
    permission: codewhitelist.command.code
    permission-message: You don't have permission to use this command.
permissions:
  codewhitelist.command.code:
    description: Allows the player to use the /code command.
    default: true